name: Code quality check
run-name: Check code quality with linters
on: [push]
jobs:
    Linters:
        runs-on: ubuntu-latest
        steps:
            - name: Copy Sources
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

            - name: Set Up JDK
              uses: actions/setup-java@v4
              with:
                 distribution: 'temurin'
                 java-version: '21'

            - uses: gradle/gradle-build-action@v3
              with:
                  cache-disabled: true

            - name: Change wrapper permissions
              run: chmod +x ./gradlew

            - name: Detekt
              shell: bash
              run: ./gradlew detekt

            - uses: jwgmeligmeyling/checkstyle-github-action@master
              with:
                 path: '**/checkstyle-result.xml'
